# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0004_auto_20160819_1811'),
        ('pythonbeltapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(related_name='whatever', to='loginreg.User'),
        ),
    ]
