# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0004_auto_20160819_1811'),
        ('pythonbeltapp', '0002_trip_travelers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='loginreg.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(related_name='travelers', to='loginreg.User'),
        ),
    ]
